language: node_js

node_js: 
  - "lts/*"

matrix:
  include:
    - os: windows
    - os: linux

script:
  - npm install gulp
  - npm install tfx-cli
  - npm install
  - gulp package --publisher travisci-build --release
  - npm test

